<?php

namespace App\Exports;

use App\Models\Product;
use App\Models\Supplier;
use App\Models\Category;
use App\Models\PurchaseOrder;
use App\Models\StockAdjustment;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Border;

class SummaryExport implements FromArray, WithHeadings, WithStyles, WithTitle, ShouldAutoSize
{
    public function array(): array
    {
        $products = Product::all();
        $suppliers = Supplier::all();
        $categories = Category::all();
        $orders = PurchaseOrder::all();
        $adjustments = StockAdjustment::all();

        return [
            ['Export Information'],
            ['Generated By', Auth::user()->name],
            ['Generated On', now()->format('F d, Y H:i:s')],
            [''],
            [''],
            ['Inventory Overview'],
            ['Total Products', $products->count()],
            ['Active Products', $products->where('status', 'active')->count()],
            ['Inactive Products', $products->where('status', 'inactive')->count()],
            ['Total Stock Value (₦)', number_format($products->sum(fn($p) => $p->stockValue), 2)],
            ['Low Stock Items', $products->filter(fn($p) => $p->current_stock <= $p->minimum_stock)->count()],
            ['Out of Stock Items', $products->where('current_stock', 0)->count()],
            [''],
            ['Supplier Statistics'],
            ['Total Suppliers', $suppliers->count()],
            ['Active Suppliers', $suppliers->where('status', 'active')->count()],
            ['Inactive Suppliers', $suppliers->where('status', 'inactive')->count()],
            [''],
            ['Category Statistics'],
            ['Total Categories', $categories->count()],
            [''],
            ['Purchase Order Statistics'],
            ['Total Orders', $orders->count()],
            ['Draft Orders', $orders->where('status', 'draft')->count()],
            ['Sent Orders', $orders->where('status', 'sent')->count()],
            ['Received Orders', $orders->where('status', 'received')->count()],
            ['Cancelled Orders', $orders->where('status', 'cancelled')->count()],
            ['Total Order Value (₦)', number_format($orders->sum('total_amount'), 2)],
            [''],
            ['Stock Movement Statistics'],
            ['Total Adjustments', $adjustments->count()],
            ['Stock In Adjustments', $adjustments->where('adjustment_type', 'in')->count()],
            ['Stock Out Adjustments', $adjustments->where('adjustment_type', 'out')->count()],
            ['Stock Corrections', $adjustments->where('adjustment_type', 'correction')->count()],
        ];
    }

    public function headings(): array
    {
        return [
            'Metric',
            'Value',
        ];
    }

    public function styles(Worksheet $sheet)
    {
        // Style header row
        $sheet->getStyle('A1:B1')->applyFromArray([
            'font' => [
                'bold' => true,
                'color' => ['rgb' => 'FFFFFF'],
            ],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => ['rgb' => '6366F1'], // Indigo
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_THIN,
                ],
            ],
        ]);

        // Style section headers (rows with single merged cell content)
        $sectionRows = [2, 7, 15, 20, 22, 31];
        foreach ($sectionRows as $row) {
            $sheet->getStyle("A{$row}:B{$row}")->applyFromArray([
                'font' => [
                    'bold' => true,
                    'size' => 12,
                ],
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'startColor' => ['rgb' => 'E5E7EB'],
                ],
            ]);
        }

        return [];
    }

    public function title(): string
    {
        return 'Summary';
    }
}
