<?php

namespace App\Livewire\Settings;

use App\Models\Product;
use App\Models\Supplier;
use App\Models\PurchaseOrder;
use App\Models\StockAdjustment;
use App\Models\Category;
use App\Models\User;
use App\Exports\CompleteDataExport;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Livewire\Component;
use Livewire\Attributes\On;
use Livewire\WithFileUploads;
use Symfony\Component\HttpFoundation\StreamedResponse;
use Maatwebsite\Excel\Facades\Excel;

class Data extends Component
{
    use WithFileUploads;

    public $actionToConfirm = null;
    public $importFile;

    protected $rules = [
        'importFile' => 'required|file|mimes:csv,txt|max:10240', // 10MB max
    ];

    public function exportCSV()
    {
        try {
            $filename = 'stockflow-complete-export-' . now()->format('Y-m-d-His') . '.csv';

            $headers = [
                'Content-Type' => 'text/csv; charset=UTF-8',
                'Content-Disposition' => 'attachment; filename="' . $filename . '"',
                'Cache-Control' => 'no-cache, no-store, must-revalidate',
                'Pragma' => 'no-cache',
                'Expires' => '0',
            ];

            $callback = function() {
                $file = fopen('php://output', 'w');

                // UTF-8 BOM
                fprintf($file, chr(0xEF).chr(0xBB).chr(0xBF));

                // === PRODUCTS SECTION ===
                fputcsv($file, ['=== PRODUCTS ===']);
                fputcsv($file, ['Generated on: ' . now()->format('F d, Y H:i:s')]);
                fputcsv($file, ['Generated by: ' . Auth::user()->name]);
                fputcsv($file, []);

                fputcsv($file, [
                    'SKU', 'Product Name', 'Barcode', 'Category', 'Supplier',
                    'Unit of Measure', 'Cost Price (₦)', 'Selling Price (₦)',
                    'Current Stock', 'Minimum Stock', 'Maximum Stock',
                    'Stock Status', 'Stock Value (₦)', 'Status', 'Created Date'
                ]);

                $products = Product::with(['category', 'supplier'])->get();
                foreach ($products as $product) {
                    fputcsv($file, [
                        $product->sku,
                        $product->name,
                        $product->barcode ?? 'N/A',
                        $product->category->name ?? 'Uncategorized',
                        $product->supplier->company_name ?? 'N/A',
                        $product->unit_of_measure,
                        number_format($product->cost_price, 2),
                        number_format($product->selling_price, 2),
                        $product->current_stock,
                        $product->minimum_stock,
                        $product->maximum_stock ?? 'N/A',
                        $product->stockStatus['status'],
                        number_format($product->stockValue, 2),
                        ucfirst($product->status),
                        $product->created_at->format('Y-m-d'),
                    ]);
                }

                fputcsv($file, []);
                fputcsv($file, ['Total Products', $products->count()]);
                fputcsv($file, []);
                fputcsv($file, []);

                // === SUPPLIERS SECTION ===
                fputcsv($file, ['=== SUPPLIERS ===']);
                fputcsv($file, []);

                fputcsv($file, [
                    'Company Name', 'Contact Person', 'Email', 'Phone',
                    'Address', 'City', 'State', 'Zip Code', 'Country',
                    'Payment Terms', 'Status', 'Total Products', 'Total Orders', 'Created Date'
                ]);

                $suppliers = Supplier::withCount(['products', 'purchaseOrders'])->get();
                foreach ($suppliers as $supplier) {
                    fputcsv($file, [
                        $supplier->company_name,
                        $supplier->contact_person ?? 'N/A',
                        $supplier->email ?? 'N/A',
                        $supplier->phone ?? 'N/A',
                        $supplier->address ?? 'N/A',
                        $supplier->city ?? 'N/A',
                        $supplier->state ?? 'N/A',
                        $supplier->zip_code ?? 'N/A',
                        $supplier->country,
                        $supplier->payment_terms ?? 'N/A',
                        ucfirst($supplier->status),
                        $supplier->products_count,
                        $supplier->purchase_orders_count,
                        $supplier->created_at->format('Y-m-d'),
                    ]);
                }

                fputcsv($file, []);
                fputcsv($file, ['Total Suppliers', $suppliers->count()]);
                fputcsv($file, []);
                fputcsv($file, []);

                // === CATEGORIES SECTION ===
                fputcsv($file, ['=== CATEGORIES ===']);
                fputcsv($file, []);

                fputcsv($file, ['Category Name', 'Description', 'Total Products', 'Created Date']);

                $categories = Category::withCount('products')->get();
                foreach ($categories as $category) {
                    fputcsv($file, [
                        $category->name,
                        $category->description ?? 'N/A',
                        $category->products_count,
                        $category->created_at->format('Y-m-d'),
                    ]);
                }

                fputcsv($file, []);
                fputcsv($file, []);

                // === PURCHASE ORDERS SECTION ===
                fputcsv($file, ['=== PURCHASE ORDERS ===']);
                fputcsv($file, []);

                fputcsv($file, [
                    'PO Number', 'Supplier', 'Order Date', 'Expected Delivery',
                    'Status', 'Total Amount (₦)', 'Items Count', 'Created By', 'Created Date'
                ]);

                $orders = PurchaseOrder::with(['supplier', 'creator'])->withCount('items')->get();
                foreach ($orders as $order) {
                    fputcsv($file, [
                        $order->po_number,
                        $order->supplier->company_name ?? 'N/A',
                        $order->order_date->format('Y-m-d'),
                        $order->expected_delivery_date?->format('Y-m-d') ?? 'N/A',
                        ucfirst($order->status),
                        number_format($order->total_amount, 2),
                        $order->items_count,
                        $order->creator->name ?? 'N/A',
                        $order->created_at->format('Y-m-d'),
                    ]);
                }

                fputcsv($file, []);
                fputcsv($file, ['Total Orders', $orders->count()]);
                fputcsv($file, []);
                fputcsv($file, []);

                // === STOCK ADJUSTMENTS SECTION ===
                fputcsv($file, ['=== STOCK ADJUSTMENTS ===']);
                fputcsv($file, []);

                fputcsv($file, [
                    'Product SKU', 'Product Name', 'Adjustment Type', 'Quantity',
                    'Reason', 'Reference', 'Adjusted By', 'Adjustment Date'
                ]);

                $adjustments = StockAdjustment::with(['product', 'adjustedBy'])->latest()->get();
                foreach ($adjustments as $adjustment) {
                    fputcsv($file, [
                        $adjustment->product->sku ?? 'N/A',
                        $adjustment->product->name ?? 'N/A',
                        ucfirst($adjustment->adjustment_type),
                        $adjustment->quantity,
                        $adjustment->reason,
                        $adjustment->reference ?? 'N/A',
                        $adjustment->adjustedBy->name ?? 'N/A',
                        $adjustment->adjustment_date->format('Y-m-d'),
                    ]);
                }

                fputcsv($file, []);
                fputcsv($file, ['Total Adjustments', $adjustments->count()]);

                fclose($file);
            };

            $this->dispatch('toast', [
                'type' => 'success',
                'message' => 'Data exported successfully!'
            ]);

            return new StreamedResponse($callback, 200, $headers);

        } catch (\Exception $e) {
            $this->dispatch('toast', [
                'type' => 'error',
                'message' => 'Export failed: ' . $e->getMessage()
            ]);
        }
    }

    public function exportExcel()
    {
        try {
            $filename = 'stockflow-complete-export-' . now()->format('Y-m-d-His') . '.xlsx';

            $this->dispatch('toast', [
                'type' => 'success',
                'message' => 'Excel file generated successfully!'
            ]);

            return Excel::download(new CompleteDataExport(), $filename);

        } catch (\Exception $e) {
            $this->dispatch('toast', [
                'type' => 'error',
                'message' => 'Excel export failed: ' . $e->getMessage()
            ]);
        }
    }

    public function updatedImportFile()
    {
        $this->validate([
            'importFile' => 'required|file|mimes:csv,txt|max:10240',
        ]);
    }

    public function importCSV()
    {
        $this->validate();

        try {
            DB::beginTransaction();

            $path = $this->importFile->getRealPath();
            $file = fopen($path, 'r');

            // Skip header rows
            for ($i = 0; $i < 5; $i++) {
                fgetcsv($file);
            }

            $imported = 0;
            $errors = [];

            while (($data = fgetcsv($file)) !== false) {
                // Skip empty rows or section headers
                if (empty($data[0]) || strpos($data[0], '===') !== false || $data[0] === 'Total Products') {
                    continue;
                }

                try {
                    $category = Category::firstOrCreate(['name' => $data[3]]);
                    $supplier = !empty($data[4]) && $data[4] !== 'N/A'
                        ? Supplier::where('company_name', $data[4])->first()
                        : null;

                    Product::updateOrCreate(
                        ['sku' => $data[0]],
                        [
                            'name' => $data[1],
                            'barcode' => $data[2] !== 'N/A' ? $data[2] : null,
                            'category_id' => $category->id,
                            'supplier_id' => $supplier?->id,
                            'unit_of_measure' => $data[5],
                            'cost_price' => (float) str_replace(',', '', $data[6]),
                            'selling_price' => (float) str_replace(',', '', $data[7]),
                            'current_stock' => (int) $data[8],
                            'minimum_stock' => (int) $data[9],
                            'maximum_stock' => $data[10] !== 'N/A' ? (int) $data[10] : null,
                            'status' => strtolower($data[13]),
                        ]
                    );

                    $imported++;
                } catch (\Exception $e) {
                    $errors[] = "Row {$imported}: " . $e->getMessage();
                }
            }

            fclose($file);

            DB::commit();

            $this->reset('importFile');

            $message = "Successfully imported {$imported} products.";
            if (!empty($errors)) {
                $message .= " " . count($errors) . " errors occurred.";
            }

            $this->dispatch('toast', [
                'type' => 'success',
                'message' => $message
            ]);

        } catch (\Exception $e) {
            DB::rollBack();

            $this->dispatch('toast', [
                'type' => 'error',
                'message' => 'Import failed: ' . $e->getMessage()
            ]);
        }
    }

    public function createBackup()
    {
        $this->dispatch('toast', [
            'type' => 'info',
            'message' => 'Database backup functionality requires server configuration. Please use your hosting panel or contact support.'
        ]);
    }

    public function restoreBackup()
    {
        $this->dispatch('toast', [
            'type' => 'warning',
            'message' => 'Backup restore is a critical operation. Please contact support or use command line.'
        ]);
    }

    public function confirmDeleteAllData()
    {
        $this->actionToConfirm = 'deleteAllData';

        $this->dispatch('showConfirmModal', [
            'title' => 'Delete All Data',
            'message' => 'Are you absolutely sure? This will permanently delete all products, suppliers, and orders. This action cannot be undone and ALL your inventory data will be lost forever.',
            'confirmText' => 'Delete Everything',
            'cancelText' => 'Cancel',
            'confirmColor' => 'red',
            'icon' => 'danger',
        ]);
    }

    public function confirmDeleteAccount()
    {
        $this->actionToConfirm = 'deleteAccount';

        $this->dispatch('showConfirmModal', [
            'title' => 'Delete Account',
            'message' => 'Are you absolutely sure? This will permanently delete your account and all associated data. You will not be able to recover your account or data after this action.',
            'confirmText' => 'Delete Account',
            'cancelText' => 'Cancel',
            'confirmColor' => 'red',
            'icon' => 'danger',
        ]);
    }

    #[On('confirmed')]
    public function handleConfirmed()
    {
        if ($this->actionToConfirm === 'deleteAllData') {
            $this->deleteAllData();
        } elseif ($this->actionToConfirm === 'deleteAccount') {
            $this->deleteAccount();
        }

        $this->actionToConfirm = null;
    }

    #[On('cancelled')]
    public function handleCancelled()
    {
        $this->actionToConfirm = null;
    }

    private function deleteAllData()
    {
        try {
            DB::beginTransaction();

            // Disable foreign key checks temporarily
            DB::statement('SET FOREIGN_KEY_CHECKS=0');

            // Delete in correct order (children first, then parents)
            DB::table('stock_adjustments')->truncate();
            DB::table('purchase_order_items')->truncate();
            DB::table('purchase_orders')->truncate();

            // Force delete all products (including soft deleted)
            DB::table('products')->delete();

            DB::table('suppliers')->truncate();

            // Keep default categories (id <= 6), delete custom ones
            DB::table('categories')->where('id', '>', 6)->delete();

            // Re-enable foreign key checks
            DB::statement('SET FOREIGN_KEY_CHECKS=1');

            // Reset auto-increment counters
            DB::statement('ALTER TABLE products AUTO_INCREMENT = 1');
            DB::statement('ALTER TABLE suppliers AUTO_INCREMENT = 1');
            DB::statement('ALTER TABLE purchase_orders AUTO_INCREMENT = 1');
            DB::statement('ALTER TABLE stock_adjustments AUTO_INCREMENT = 1');

            DB::commit();

            $this->dispatch('toast', [
                'type' => 'success',
                'message' => 'All inventory data has been deleted successfully!'
            ]);

            return redirect()->route('dashboard');

        } catch (\Exception $e) {
            DB::rollBack();

            $this->dispatch('toast', [
                'type' => 'error',
                'message' => 'Failed to delete data: ' . $e->getMessage()
            ]);
        }
    }

    private function deleteAccount()
    {
        try {
            $user = Auth::user();

            $adminCount = User::role('Admin')->count();
            if ($adminCount === 1 && $user->hasRole('Admin')) {
                $this->dispatch('toast', [
                    'type' => 'error',
                    'message' => 'Cannot delete account. You are the only admin. Please assign another admin first.'
                ]);
                return;
            }

            DB::beginTransaction();

            StockAdjustment::where('adjusted_by', $user->id)->delete();
            PurchaseOrder::where('created_by', $user->id)->update(['created_by' => null]);

            $user->delete();

            DB::commit();

            Auth::logout();

            session()->invalidate();
            session()->regenerateToken();

            return redirect()->route('login')->with('toast', [
                'type' => 'success',
                'message' => 'Your account has been deleted successfully.'
            ]);

        } catch (\Exception $e) {
            DB::rollBack();

            $this->dispatch('toast', [
                'type' => 'error',
                'message' => 'Failed to delete account: ' . $e->getMessage()
            ]);
        }
    }

    public function render()
    {
        $stats = [
            'total_products' => Product::count(),
            'total_suppliers' => Supplier::count(),
            'total_categories' => Category::count(),
            'total_orders' => PurchaseOrder::count(),
            'total_adjustments' => StockAdjustment::count(),
        ];

        return view('livewire.settings.data', compact('stats'));
    }
}
